version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: local
    environment:
      POSTGRES_USER: dbeaver_user
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: ecommerce_db
    ports:
      - "5433:5432"               # ?????? 5433 ??? ??? host ????? ??????? ??????
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:

networks:
  productmicroservice-network:
    external: true
